### ISSUE TITLE
Move hosting to GitHub Pages

### ISSUE THREAD

**Issue by johnkary** [jefftriplett/daysuntillatenight.com#4]

**Comment by jefftriplett** [comment]
I can help with this at some point if you have questions. I really like the `_data` / collections format. It makes it easy to have structured data and not just a blog.

**Comment by johnkary** [comment]
@jefftriplett Thanks, I think I have it working.

http://daysuntillatenight.com is now hosted from GitHub Pages. Any commits on `master` branch will display on the site.
